### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Hirdyanshbhalla** [mojipkfr77/instacr#1]
Sorry Bro , but i am having problems running your script in kali linux , i followed all steps but finally it says no such file or directory exists , can you explain more clearly how to use your script ???

**Comment by mojipkfr77** [comment]
sorry , if you are using 64Bit OS , you have to install some packages for running 32 bit bins on 64 bit 
open terminal and write these commands :

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 && sudo apt-get install zlib1g:i386

then run program:
./InstaBrute

**Comment by mojipkfr77** [comment]
sorry , if you are using 64Bit OS , you have to install some packages for running 32 bit bins on 64 bit 
open terminal and write these commands :

sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 && sudo apt-get install zlib1g:i386

then run program:
./InstaBrute

**Comment by mojipkfr77** [comment]
sorry , if you are using 64Bit OS , you have to install some packages for
running 32 bit bins on 64 bit

open terminal and write these commands :


sudo dpkg --add-architecture i386

sudo apt-get update

sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

sudo apt-get install libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 &&
sudo apt-get install zlib1g:i386


then run program:

./InstaBrute



در تاریخ ۷ ژانویهٔ ۲۰۱۸ ۴:۵۵ بعدازظهر، "Hirdyanshbhalla" <
notifications@github.com> نوشت:
